DROP TABLE MEMBER
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_MEMBER;

CREATE TABLE MEMBER (
	SEQ NUMBER(20) NOT NULL,
	ID VARCHAR2(50) PRIMARY KEY,
    	NAME VARCHAR2(50) UNIQUE,
	PWD VARCHAR2(50) NOT NULL,
	EMAIL VARCHAR2(50) UNIQUE, 
   	 AUTH NUMBER(1) NOT NULL,
    	LOC VARCHAR2(50) NOT NULL
);

CREATE SEQUENCE SEQ_MEMBER
START WITH 1 INCREMENT BY 1;



-----------------------------


DROP TABLE CREW
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_CREW;

CREATE TABLE CREW(
	 SEQ NUMBER(8) PRIMARY KEY,
	 GNAME VARCHAR2(50) NOT NULL,
	 LOC VARCHAR2(50) NOT NULL,
	 PERIOD VARCHAR2(20) NOT NULL,
	 CREWDATE VARCHAR2(100) NOT NULL,
	 CURCOUNT NUMBER(8) NOT NULL,
	 MAXCOUNT NUMBER(8) NOT NULL,
	 CONTENT VARCHAR2(2000) NOT NULL,
	 FILENAME VARCHAR2(200) NOT NULL,
	 NEWFILEPATH VARCHAR2(200) NOT NULL,
	 LEADERID VARCHAR2(50) NOT NULL,
 	 LEADERNAME VARCHAR2(50) NOT NULL,
	 MEETLOC VARCHAR2(200),
	 COURSE VARCHAR2(200)
);

CREATE SEQUENCE SEQ_CREW
START WITH 1 INCREMENT BY 1;

ALTER TABLE CREW
ADD CONSTRAINT FK_CR_ID FOREIGN KEY(LEADERID)
REFERENCES MEMBER(ID);



-----------------------------


DROP TABLE CALENDAR
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_CAL;

CREATE TABLE CALENDAR(
	SEQ NUMBER(8) PRIMARY KEY,
    CREWID NUMBER(8) NOT NULL,
	ID VARCHAR2(50) NOT NULL,
    NAME VARCHAR2(50) NOT NULL,
	TITLE VARCHAR2(200) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	RDATE VARCHAR2(50) NOT NULL,
	WDATE DATE NOT NULL,
    LABELCOL VARCHAR2(50) NOT NULL
);


CREATE SEQUENCE SEQ_CAL
START WITH 1
INCREMENT BY 1;

ALTER TABLE CALENDAR
ADD CONSTRAINT FK_CAL_ID FOREIGN KEY(ID)
REFERENCES MEMBER(ID);

ALTER TABLE CALENDAR
ADD CONSTRAINT FK_CREWID_ID FOREIGN KEY(CREWID)
REFERENCES CREW(SEQ);



-----------------------------


DROP TABLE PDS
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_PDS;

CREATE TABLE PDS(
	SEQ NUMBER(8) PRIMARY KEY,
	ID VARCHAR2(50) NOT NULL,
    NAME VARCHAR2(50) NOT NULL,
	TITLE VARCHAR2(200) NOT NULL,
	CONTENT VARCHAR2(4000),
	FILENAME VARCHAR2(50) ,
	NEWFILENAME VARCHAR2(50) ,
	READCOUNT NUMBER(8) NOT NULL,
    PDSNUM NUMBER(1) NOT NULL,
	REGDATE DATE NOT NULL
);

CREATE SEQUENCE SEQ_PDS
START WITH 1 INCREMENT BY 1;

ALTER TABLE PDS
ADD CONSTRAINT FK_PDS_NAME FOREIGN KEY(ID)
REFERENCES MEMBER(ID);

-----------------------------

DROP TABLE BBS
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_BBS;

CREATE TABLE BBS(
	SEQ NUMBER(8) PRIMARY KEY,
    BBSID NUMBER(8) NOT NULL,
	ID VARCHAR2(50) NOT NULL,	-- 글의 작성자	
    NAME VARCHAR2(50) NOT NULL,
	TITLE VARCHAR2(200) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	WDATE DATE NOT NULL,	
    FILENAME VARCHAR2(50) ,
	NEWFILENAME VARCHAR2(50) ,
	READCOUNT NUMBER(8) NOT NULL
);

CREATE SEQUENCE SEQ_BBS
START WITH 1
INCREMENT BY 1;

ALTER TABLE BBS
ADD CONSTRAINT FK_BBS_NAME FOREIGN KEY(ID)
REFERENCES MEMBER(ID);

-----------------------------


DROP TABLE CREWBBS
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_CREWBBS;


CREATE TABLE CREWBBS(
    SEQ NUMBER(8) PRIMARY KEY,
    BBSID NUMBER(8) NOT NULL,
    ID VARCHAR2(50) NOT NULL,
    NAME VARCHAR2(50) NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    CONTENT VARCHAR2(4000) NOT NULL,
    FILENAME VARCHAR2(50) ,
    NEWFILENAME VARCHAR2(50) ,
    READCOUNT NUMBER(8) NOT NULL,
    LIKECOUNT NUMBER(8) NOT NULL,
    COMCOUNT NUMBER(8) NOT NULL,
    REGDATE DATE NOT NULL

);

CREATE SEQUENCE SEQ_CREWBBS
START WITH 1
INCREMENT BY 1;



ALTER TABLE CREWBBS
ADD CONSTRAINT FK_CREWBBS_ID FOREIGN KEY(ID)
REFERENCES MEMBER(ID);

-----------------------------

DROP TABLE COMMENTDB
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_COMMENT;
DROP SEQUENCE SEQ_COMSTEP;

CREATE TABLE COMMENTDB(
    SEQ NUMBER(8) PRIMARY KEY,		--번호
    BBSID NUMBER(8) NOT NULL,		--게시판번호
    COMSTEP NUMBER(8) NOT NULL,		--게시글번호
    ID VARCHAR2(50) NOT NULL,		--작성자
    NAME VARCHAR2(50) NOT NULL,		--이름
    REGDATE  DATE NOT NULL,		--작성일
    CONTENT  VARCHAR2(200) NOT NULL,	--내용
    LIKECOUNT  NUMBER(8) NOT NULL,		--좋아요
    DISLIKECOUNT  NUMBER(8) NOT NULL	--싫어요
);

CREATE SEQUENCE SEQ_COMMENT
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_COMSTEP
START WITH 1
INCREMENT BY 1;

ALTER TABLE COMMENTDB
ADD CONSTRAINT FK_COM_ID FOREIGN KEY(ID)
REFERENCES MEMBER(ID);



-----------------------------


DROP TABLE CHAT
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_CHAT;


CREATE TABLE CHAT(
    SEQ NUMBER(8) PRIMARY KEY,
    CHATNUM NUMBER(8) NOT NULL,
    ID VARCHAR2(50) NOT NULL,
    NAME VARCHAR2(50) NOT NULL,
    REGTIME VARCHAR2(50) NOT NULL,
    CONTENT VARCHAR2(50) NOT NULL
);

CREATE SEQUENCE SEQ_CHAT
START WITH 1
INCREMENT BY 1;


ALTER TABLE CHAT
ADD CONSTRAINT FK_CHAT_NUM FOREIGN KEY(CHATNUM)
REFERENCES CREW(SEQ);


ALTER TABLE CHAT
ADD CONSTRAINT FK_CHAT_ID FOREIGN KEY(ID)
REFERENCES MEMBER(ID);

-----------------------------

DROP TABLE REPORTBBS
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_REPORTBBS;

CREATE TABLE REPORTBBS(
    SEQ NUMBER(8) PRIMARY KEY,
    BBSID NUMBER(8) NOT NULL,
    BBSNUM NUMBER(8) NOT NULL,
    COMMENTNUM NUMBER(8) ,
    TITLE VARCHAR2(200) NOT NULL,
    REASON VARCHAR2(200) NOT NULL,
    COUNTUSER VARCHAR2(50) NOT NULL,
    ENCOUNTUSER VARCHAR2(50) NOT NULL
    
);

CREATE SEQUENCE SEQ_REPORTBBS
START WITH 1
INCREMENT BY 1;

ALTER TABLE REPORTBBS
ADD CONSTRAINT FK_REBBS_BBSNUM FOREIGN KEY(BBSNUM)
REFERENCES BBS(SEQ);

-----------------------------
DROP TABLE CREWMEMBER
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_CREWMEMBER;


CREATE TABLE CREWMEMBER(
    SEQ NUMBER(8) PRIMARY KEY,
    CREWNUM NUMBER(8) NOT NULL,
    MEMBER_ID VARCHAR2(50) NOT NULL,
    MEMBER_NAME VARCHAR2(50) NOT NULL
);

CREATE SEQUENCE SEQ_CREWMEMBER
START WITH 1
INCREMENT BY 1;

ALTER TABLE CREWMEMBER
ADD CONSTRAINT FK_CRMEM_CRNUM FOREIGN KEY(CREWNUM)
REFERENCES CREW(SEQ);

ALTER TABLE CREWMEMBER
ADD CONSTRAINT FK_CRMEM_MEMNAME FOREIGN KEY(MEMBER_ID)
REFERENCES MEMBER(ID);

COMMIT;

